# Generated by Django 3.2.15 on 2023-05-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0004_auto_20230523_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='correct_document',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='estate_reg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='file',
            name='headline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_notified',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_personal_notified',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='phone_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='file',
            name='ref_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
