# Generated by Django 3.2.15 on 2023-09-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0008_auto_20230915_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='delineation_tax_value2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='license_value2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='payment_receipt_date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='payment_receipt_number2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
