# Generated by Django 3.2.15 on 2023-10-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0009_auto_20230916_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='official_letter_issued',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
