# Generated by Django 3.2.15 on 2023-10-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0010_file_official_letter_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='official_letter_issued',
            field=models.DateField(blank=True, null=True),
        ),
    ]
