# Generated by Django 3.2.15 on 2023-10-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0012_auto_20231012_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='observation_list',
        ),
        migrations.RemoveField(
            model_name='operatorobservation',
            name='name',
        ),
        migrations.AddField(
            model_name='operatorobservation',
            name='fileID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observationList', to='filed.file'),
        ),
        migrations.AddField(
            model_name='operatorobservation',
            name='observation',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
