# Generated by Django 3.2.15 on 2023-10-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0013_auto_20231012_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorobservation',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
