# Generated by Django 3.2.15 on 2023-11-15 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filed', '0015_auto_20231115_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggerall',
            name='action',
            field=models.CharField(choices=[('update', 'update'), ('create', 'create'), ('delete', 'delete'), ('empty', 'empty')], default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='loggerall',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
